items:

  - id: AST_LAYOUT_TYPE_PARAGRAPH
    upper_name: "PARAGRAPH"
    lower_name: "paragraph"
    generate_name: "p"
    text: "پاراگراف"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_PARAGRAPH_RAW
    upper_name: "PARAGRAPH_RAW"
    lower_name: "paragraph_raw"
    generate_name: "content"
    text: "محتوا"
    is_mother: false
    is_hide: true

  - id: AST_LAYOUT_TYPE_BUTTON
    upper_name: "BUTTON"
    lower_name: "button"
    generate_name: "button"
    text: "دکمه"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_TEXTAREA
    upper_name: "TEXTAREA"
    lower_name: "textarea"
    generate_name: "textarea"
    text: "ویرایشگرمتن"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_TEXTAREA_REPEAT
    upper_name: "TEXTAREA"
    lower_name: "textarea"
    generate_name: "textarea"
    text: "ویرایشگر متن"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_LABEL
    upper_name: "LABEL"
    lower_name: "label"
    generate_name: "label"
    text: "برچسب"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_SELECT
    upper_name: "SELECT"
    lower_name: "select"
    generate_name: "select"
    text: "فهرست کشویی"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_OPTION
    upper_name: "OPTION"
    lower_name: "option"
    generate_name: "option"
    text: "مورد کشویی"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_FIELDSET
    upper_name: "FIELDSET"
    lower_name: "fieldset"
    generate_name: "fieldset"
    text: "گروه‌بندی"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_FIELDSET_REPEAT
    upper_name: "FIELDSET"
    lower_name: "fieldset"
    generate_name: "fieldset"
    text: "گروه بندی"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_LEGEND
    upper_name: "LEGEND"
    lower_name: "legend"
    generate_name: "legend"
    text: "عنوان گروه"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_FORM
    upper_name: "FORM"
    lower_name: "form"
    generate_name: "form"
    text: "فرم"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_OPTGROUP
    upper_name: "OPTGROUP"
    lower_name: "optgroup"
    generate_name: "optgroup"
    text: "گروه انتخاب"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_DATALIST
    upper_name: "DATALIST"
    lower_name: "datalist"
    generate_name: "datalist"
    text: "داده فهرست"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_OUTPUT
    upper_name: "OUTPUT"
    lower_name: "output"
    generate_name: "output"
    text: "خروجی"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_KEYGEN
    upper_name: "KEYGEN"
    lower_name: "keygen"
    generate_name: "keygen"
    text: "تولید کلید"
    is_mother: false
    is_hide: false

  - id: AST_LAYOUT_TYPE_SPAN
    upper_name: "SPAN"
    lower_name: "span"
    generate_name: "span"
    text: "قطعه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_STRONG
    upper_name: "STRONG"
    lower_name: "strong"
    generate_name: "strong"
    text: "ضخیم مهم"
    is_mother: false

  - id: AST_LAYOUT_TYPE_EM
    upper_name: "EM"
    lower_name: "em"
    generate_name: "em"
    text: "ایتالیک پیشرفته"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ITALIC
    upper_name: "ITALIC"
    lower_name: "italic"
    generate_name: "i"
    text: "ایتالیک"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BOLD
    upper_name: "BOLD"
    lower_name: "bold"
    generate_name: "b"
    text: "ضخیم"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUBTITLE
    upper_name: "SUBTITLE"
    lower_name: "subtitle"
    generate_name: "subtitle"
    text: "سرتیتر"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUBTITLE_REPEAT
    upper_name: "SUBTITLE"
    lower_name: "subtitle"
    generate_name: "subtitle"
    text: "سر تیتر"
    is_mother: false

  - id: AST_LAYOUT_TYPE_UNDERLINE
    upper_name: "UNDERLINE"
    lower_name: "underline"
    generate_name: "u"
    text: "زیرخط"
    is_mother: false

  - id: AST_LAYOUT_TYPE_UNDERLINE_REPEAT
    upper_name: "UNDERLINE"
    lower_name: "underline"
    generate_name: "u"
    text: "زیر خط"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SMALL
    upper_name: "SMALL"
    lower_name: "small"
    generate_name: "small"
    text: "کوچک"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BIG
    upper_name: "BIG"
    lower_name: "big"
    generate_name: "big"
    text: "بزرگ"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUB
    upper_name: "SUB"
    lower_name: "sub"
    generate_name: "sub"
    text: "زیرین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUP
    upper_name: "SUP"
    lower_name: "sup"
    generate_name: "sup"
    text: "رویین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_S
    upper_name: "S"
    lower_name: "s"
    generate_name: "s"
    text: "خط خورده"
    is_mother: false

  - id: AST_LAYOUT_TYPE_MARK
    upper_name: "MARK"
    lower_name: "mark"
    generate_name: "mark"
    text: "علامتگذاری"
    is_mother: false

  - id: AST_LAYOUT_TYPE_MARK_REPEAT
    upper_name: "MARK"
    lower_name: "mark"
    generate_name: "mark"
    text: "علامت گذاری"
    is_mother: false

  - id: AST_LAYOUT_TYPE_Q
    upper_name: "Q"
    lower_name: "q"
    generate_name: "q"
    text: "نقل قول"
    is_mother: false

  - id: AST_LAYOUT_TYPE_Q_REPEAT
    upper_name: "Q"
    lower_name: "q"
    generate_name: "q"
    text: "نقل‌قول"
    is_mother: false

  - id: AST_LAYOUT_TYPE_CITE
    upper_name: "CITE"
    lower_name: "cite"
    generate_name: "cite"
    text: "اثر"
    is_mother: false

  - id: AST_LAYOUT_TYPE_CITE_REPEAT
    upper_name: "CITE"
    lower_name: "cite"
    generate_name: "cite"
    text: "ارجاع"
    is_mother: false

  - id: AST_LAYOUT_TYPE_DFN
    upper_name: "DFN"
    lower_name: "dfn"
    generate_name: "dfn"
    text: "اصطلاح"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ABBR
    upper_name: "ABBR"
    lower_name: "abbr"
    generate_name: "abbr"
    text: "اختصار"
    is_mother: false

  - id: AST_LAYOUT_TYPE_KBD
    upper_name: "KBD"
    lower_name: "kbd"
    generate_name: "kbd"
    text: "ورودی صفحه نمایش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_KBD_REPEAT
    upper_name: "KBD"
    lower_name: "kbd"
    generate_name: "kbd"
    text: "ورودی کیبورد"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SAMP
    upper_name: "SAMP"
    lower_name: "samp"
    generate_name: "samp"
    text: "نمونه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_VAR
    upper_name: "VAR"
    lower_name: "var"
    generate_name: "var"
    text: "متغیر"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RUBY
    upper_name: "RUBY"
    lower_name: "ruby"
    generate_name: "ruby"
    text: "روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RT
    upper_name: "RT"
    lower_name: "rt"
    generate_name: "rt"
    text: "متن روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RP
    upper_name: "RP"
    lower_name: "rp"
    generate_name: "rp"
    text: "جایگزین روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BDI
    upper_name: "BDI"
    lower_name: "bdi"
    generate_name: "bdi"
    text: "جداگانه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BDO
    upper_name: "BDO"
    lower_name: "bdo"
    generate_name: "bdo"
    text: "جهت دهی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_WBR
    upper_name: "WBR"
    lower_name: "wbr"
    generate_name: "wbr"
    text: "شکستن کلمه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HEADER
    upper_name: "HEADER"
    lower_name: "header"
    generate_name: "header"
    text: "سربخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HEADER_REPEAT
    upper_name: "HEADER"
    lower_name: "header"
    generate_name: "header"
    text: "سر بخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_FOOTER
    upper_name: "FOOTER"
    lower_name: "footer"
    generate_name: "footer"
    text: "پاصفحه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_FOOTER_REPEAT
    upper_name: "FOOTER"
    lower_name: "footer"
    generate_name: "footer"
    text: "پا صفحه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_NAV
    upper_name: "NAV"
    lower_name: "nav"
    generate_name: "nav"
    text: "ناوبری"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SECTION
    upper_name: "SECTION"
    lower_name: "section"
    generate_name: "section"
    text: "بخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ARTICLE
    upper_name: "ARTICLE"
    lower_name: "article"
    generate_name: "article"
    text: "مقاله"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ASIDE
    upper_name: "ASIDE"
    lower_name: "aside"
    generate_name: "aside"
    text: "جداگانه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ASIDE_REPEAT
    upper_name: "ASIDE"
    lower_name: "aside"
    generate_name: "aside"
    text: "جدا گانه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_MAIN
    upper_name: "MAIN"
    lower_name: "main"
    generate_name: "main"
    text: "اصلی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HGROUP
    upper_name: "HGROUP"
    lower_name: "hgroup"
    generate_name: "hgroup"
    text: "گروه سربخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HGROUP_REPEAT
    upper_name: "HGROUP"
    lower_name: "hgroup"
    generate_name: "hgroup"
    text: "گروه‌سربخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HGROUP_REPEAT_ALT
    upper_name: "HGROUP"
    lower_name: "hgroup"
    generate_name: "hgroup"
    text: "گروه‌سر بخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HGROUP_REPEAT_ALT2
    upper_name: "HGROUP"
    lower_name: "hgroup"
    generate_name: "hgroup"
    text: "گروه سر بخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_FIGURE
    upper_name: "FIGURE"
    lower_name: "figure"
    generate_name: "figure"
    text: "شکل"
    is_mother: false

  - type: AST_LAYOUT_TYPE_FIGCAPTION
    name: "FIGCAPTION"
    tag: "figcaption"
    start_tag: "figcaption"
    description: "زیرنویس شکل"
    repeat: false

  - type: AST_LAYOUT_TYPE_FIGCAPTION
    name: "FIGCAPTION"
    tag: "figcaption"
    start_tag: "figcaption"
    description: "زیر نویس شکل"
    repeat: true

  - type: AST_LAYOUT_TYPE_VIDEO
    name: "VIDEO"
    tag: "video"
    start_tag: "video"
    description: "فیلم"
    repeat: false

  - type: AST_LAYOUT_TYPE_AUDIO
    name: "AUDIO"
    tag: "audio"
    start_tag: "audio"
    description: "صدا"
    repeat: false

  - type: AST_LAYOUT_TYPE_IFRAME
    name: "IFRAME"
    tag: "iframe"
    start_tag: "iframe"
    description: "سایت"
    repeat: false

  - type: AST_LAYOUT_TYPE_CANVAS
    name: "CANVAS"
    tag: "canvas"
    start_tag: "canvas"
    description: "گرافیکی"
    repeat: false

  - type: AST_LAYOUT_TYPE_DETAILS
    name: "DETAILS"
    tag: "details"
    start_tag: "details"
    description: "جزئیات"
    repeat: false

  - type: AST_LAYOUT_TYPE_DETAILS
    name: "DETAILS"
    tag: "details"
    start_tag: "details"
    description: "جزییات"
    repeat: true

  - type: AST_LAYOUT_TYPE_SUMMARY
    name: "SUMMARY"
    tag: "summary"
    start_tag: "summary"
    description: "خلاصه"
    repeat: false

  - type: AST_LAYOUT_TYPE_DIALOG
    name: "DIALOG"
    tag: "dialog"
    start_tag: "dialog"
    description: "دیالوگ"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENU
    name: "MENU"
    tag: "menu"
    start_tag: "menu"
    description: "منو"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENUITEM
    name: "MENUITEM"
    tag: "menuitem"
    start_tag: "menuitem"
    description: "آیتم منو"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENUITEM
    name: "MENUITEM"
    tag: "menuitem"
    start_tag: "menuitem"
    description: "مورد منو"
    repeat: true

  - type: AST_LAYOUT_TYPE_COMMAND
    name: "COMMAND"
    tag: "command"
    start_tag: "command"
    description: "فرمان"
    repeat: false

  - type: AST_LAYOUT_TYPE_UL
    name: "UL"
    tag: "ul"
    start_tag: "ul"
    description: "فهرست غیرمرتب"
    repeat: false

  - type: AST_LAYOUT_TYPE_UL
    name: "UL"
    tag: "ul"
    start_tag: "ul"
    description: "فهرست غیر مرتب"
    repeat: true

  - type: AST_LAYOUT_TYPE_OL
    name: "OL"
    tag: "ol"
    start_tag: "ol"
    description: "فهرست مرتب"
    repeat: false

  - type: AST_LAYOUT_TYPE_LI
    name: "LI"
    tag: "li"
    start_tag: "li"
    description: "مورد"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE
    name: "TABLE"
    tag: "table"
    start_tag: "table"
    description: "جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_HEADER
    name: "TABLE_HEADER"
    tag: "table_header"
    start_tag: "thead"
    description: "سرجدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_HEADER
    name: "TABLE_HEADER"
    tag: "table_header"
    start_tag: "thead"
    description: "سر جدول"
    repeat: true

  - type: AST_LAYOUT_TYPE_TABLE_BODY
    name: "TABLE_BODY"
    tag: "table_body"
    start_tag: "tbody"
    description: "بدنه جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_FOOTER
    name: "TABLE_FOOTER"
    tag: "table_footer"
    start_tag: "tfoot"
    description: "پاصفحه جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_FOOTER
    name: "TABLE_FOOTER"
    tag: "table_footer"
    start_tag: "tfoot"
    description: "پا صفحه جدول"
    repeat: true

  - type: AST_LAYOUT_TYPE_TABLE_TR
    name: "TABLE_TR"
    tag: "table_tr"
    start_tag: "tr"
    description: "ردیف"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TD
    name: "TABLE_TD"
    tag: "table_td"
    start_tag: "td"
    description: "سلول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TH
    name: "TABLE_TH"
    tag: "table_th"
    start_tag: "th"
    description: "سرسلول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TH
    name: "TABLE_TH"
    tag: "table_th"
    start_tag: "th"
    description: "سر سلول"
    repeat: true

  - type: AST_LAYOUT_TYPE_CAPTION
    name: "CAPTION"
    tag: "caption"
    start_tag: "caption"
    description: "عنوان جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_COL
    name: "COL"
    tag: "col"
    start_tag: "th"
    description: "ستون"
    repeat: false

  - type: AST_LAYOUT_TYPE_COLGROUP
    name: "COLGROUP"
    tag: "colgroup"
    start_tag: "colgroup"
    description: "گروه ستون‌ها"
    repeat: false

  - type: AST_LAYOUT_TYPE_COLGROUP
    name: "COLGROUP"
    tag: "colgroup"
    start_tag: "colgroup"
    description: "گروه ستون‌ ها"
    repeat: true

  - type: AST_LAYOUT_TYPE_INCLUDE
    name: INCLUDE
    tag: "include"
    html_tag: "include"
    translation: "فراخوانی"
    self_closing: true

  - type: AST_LAYOUT_TYPE_BR
    name: BR
    tag: "br"
    html_tag: "br"
    translation: "خط بعدی"
    self_closing: true

  - type: AST_LAYOUT_TYPE_HR
    name: HR
    tag: "hr"
    html_tag: "hr"
    translation: "خط"
    self_closing: true

  - type: AST_LAYOUT_TYPE_INPUT
    name: INPUT
    tag: "input"
    html_tag: "input"
    translation: "ورودی"
    self_closing: true

  - type: AST_LAYOUT_TYPE_IMG
    name: IMG
    tag: "img"
    html_tag: "img"
    translation: "تصویر"
    self_closing: true

  - type: AST_LAYOUT_TYPE_FONT
    name: FONT
    tag: "font"
    html_tag: "font"
    translation: "فونت"
    self_closing: true

  - type: AST_LAYOUT_TYPE_MEDIA
    name: RESPONSIVE
    tag: "responsive"
    html_tag: "@media"
    translation: "واکنش گرا"
    self_closing: true

  - type: AST_LAYOUT_TYPE_MEDIA
    name: RESPONSIVE
    tag: "responsive"
    html_tag: "@media"
    translation: "واکنش‌گرا"
    self_closing: true

  - type: AST_LAYOUT_TYPE_NONE
    name: NONE
    tag: "none"
    html_tag: "layout"
    translation: "صفحه"
    self_closing: false

  - type: AST_LAYOUT_TYPE_ERROR
    name: ERROR
    tag: "error"
    html_tag: "error"
    translation: "خطا"
    self_closing: false
