items:

  - id: AST_TYPE_IF
    upper_name: "IF"
    lower_name: "if"

  - id: AST_TYPE_ELSE_IF
    upper_name: "ELSE_IF"
    lower_name: "else if"

  - id: AST_TYPE_BLOCK
    upper_name: "BLOCK"
    lower_name: "block"

  - id: AST_TYPE_RETURN
    upper_name: "RETURN"
    lower_name: "return"

  - id: AST_TYPE_IMPORT
    upper_name: "IMPORT"
    lower_name: "import"

  - id: AST_TYPE_PRINT
    upper_name: "PRINT"
    lower_name: "print"

  - id: AST_TYPE_FUNCTION
    upper_name: "FUNCTION"
    lower_name: "function"

  - id: AST_TYPE_LAYOUT
    upper_name: "LAYOUT"
    lower_name: "layout"

  - id: AST_TYPE_ERROR
    upper_name: "ERROR"
    lower_name: "error"
