items:
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_ERROR
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_GROUP
    generate_name: group
    text:
      en: group
      fa: گروه
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
    generate_name: class
    text:
      en: class
      fa: کلاس
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_ID
    generate_name: id
    text:
      en: id
      fa: شناسه
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
    generate_name: content
    text:
      en: content
      fa: محتوا
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_SRC
    generate_name: src
    text:
      en: src
      fa: منبع
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
    generate_name: repeat
    text:
      en: repeat
      fa: تکرار
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_DIR
    generate_name: dir
    text:
      en: dir
      fa: جهت
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_LANG
    generate_name: lang
    text:
      en: lang
      fa: زبان
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_TITLE
    generate_name: title
    text:
      en: title
      fa: عنوان
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_TYPE
    generate_name: type
    text:
      en: type
      fa: نوع
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_AUTHOR
    generate_name: author
    text:
      en: author
      fa: نویسنده
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_DESCRIPTION
    generate_name: description
    text:
      en: description
      fa: توضیح
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_KEYWORDS
    generate_name: keywords
    text:
      en: keywords
      fa: کلمات
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_ICON
    generate_name: icon
    text:
      en: icon
      fa: نمایه
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_NAME
    generate_name: name
    text:
      en: name
      fa: نام
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_CHARSET
    generate_name: charset
    text:
      en: charset
      fa: فرمت متنی
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_REFRESH
    generate_name: refresh
    text:
      en: refresh
      fa: بروزرسانی
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_VIEWPORT
    generate_name: viewport
    text:
      en: viewport
      fa: محدوده نمایش
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_VALUE
    generate_name: value
    text:
      en: value
      fa: مقدار
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_PLACEHOLDER
    generate_name: placeholder
    text:
      en: placeholder
      fa: راهنما
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_REQUIRED
    generate_name: required
    text:
      en: required
      fa: اجباری
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_FONT_UNICODE_RANGE
    generate_name: unicode-range
    text:
      en: reunicode-range
      fa: محدود یونیکد
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_FONT_WEIGHT
    generate_name: font-weight
    text:
      en: font-weight
      fa: وزن
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_FONT_STYLE
    generate_name: font-style
    text:
      en: font-style
      fa: سبک
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_WIDTH
    generate_name: media-max-width
    text:
      en: media-max-width
      fa: شرط حداکثر عرض
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_HEIGHT
    generate_name: media-max-height
    text:
      en: media-max-height
      fa: شرط حداکثر ارتفاع
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_WIDTH
    generate_name: media-min-width
    text:
      en: media-min-width
      fa: شرط حداقل عرض
  - type: AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_HEIGHT
    generate_name: media-min-height
    text:
      en: media-min-height
      fa: شرط حداقل ارتفاع
