items:

  # Hidden items
  - id: AST_LAYOUT_TYPE_PARAGRAPH_RAW
    text:
      en: content
      fa: محتوا
    is_mother: false

  - type: AST_LAYOUT_TYPE_ERROR
    text:
      en: error
      fa: خطا
    is_mother: false

  - type: AST_LAYOUT_TYPE_NONE
    text:
      en: layout
      fa: صفحه
    is_mother: false

  #Real items
  - id: AST_LAYOUT_TYPE_PARAGRAPH
    generate_name: "p"
    text:
      en: paragraph
      fa: پاراگراف
    is_mother: false

  - id: AST_LAYOUT_TYPE_BUTTON
    generate_name: "button"
    text:
      en: "button"
      fa: "دکمه"
    is_mother: true

  - id: AST_LAYOUT_TYPE_TEXTAREA
    generate_name: "textarea"
    text:
      en: "textarea"
      fa: ["ویرایشگرمتن", "ویرایشگر متن"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_LABEL
    generate_name: "label"
    text:
      en: "label"
      fa: "برچسب"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SELECT
    generate_name: "select"
    text:
      en: "select"
      fa: "فهرست کشویی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_OPTION
    generate_name: "option"
    text:
      en: "option"
      fa: "مورد کشویی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_FIELDSET
    generate_name: "fieldset"
    text:
      en: "fieldset"
      fa: ["گروه‌بندی", "گروه بندی"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_LEGEND
    generate_name: "legend"
    text:
      en: "legend"
      fa: "عنوان گروه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_FORM
    generate_name: "form"
    text:
      en: "form"
      fa: "فرم"
    is_mother: false

  - id: AST_LAYOUT_TYPE_OPTGROUP
    generate_name: "optgroup"
    text:
      en: "optgroup"
      fa: "گروه انتخاب"
    is_mother: false

  - id: AST_LAYOUT_TYPE_DATALIST
    generate_name: "datalist"
    text:
      en: "datalist"
      fa: "داده فهرست"
    is_mother: false

  - id: AST_LAYOUT_TYPE_OUTPUT
    generate_name: "output"
    text:
      en: "output"
      fa: "خروجی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_KEYGEN
    generate_name: "keygen"
    text:
      en: "keygen"
      fa: "تولید کلید"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SPAN
    generate_name: "span"
    text:
      en: "span"
      fa: "قطعه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_STRONG
    generate_name: "strong"
    text:
      en: "strong"
      fa: "ضخیم مهم"
    is_mother: false

  - id: AST_LAYOUT_TYPE_EM
    generate_name: "em"
    text:
      en: "em"
      fa: "ایتالیک پیشرفته"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ITALIC
    generate_name: "i"
    text:
      en: "italic"
      fa: "ایتالیک"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BOLD
    generate_name: "b"
    text:
      en: "bold"
      fa: "ضخیم"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUBTITLE
    generate_name: "subtitle"
    text:
      en: "subtitle"
      fa: ["سرتیتر", "سر تیتر"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_UNDERLINE
    generate_name: "u"
    text:
      en: "underline"
      fa: ["زیرخط", "زیر خط"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_SMALL
    generate_name: "small"
    text:
      en: "small"
      fa: "کوچک"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BIG
    generate_name: "big"
    text:
      en: "big"
      fa: "بزرگ"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUB
    generate_name: "sub"
    text:
      en: "sub"
      fa: "زیرین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SUP
    generate_name: "sup"
    text:
      en: "sup"
      fa: "رویین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_S
    generate_name: "s"
    text:
      en: "s"
      fa: "خط خورده"
    is_mother: false

  - id: AST_LAYOUT_TYPE_MARK
    generate_name: "mark"
    text:
      en: "mark"
      fa: ["علامتگذاری", "علامت گذاری"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_Q
    upper_name: "Q"
    lower_name: "q"
    generate_name: "q"
      fa: ["نقل قول", "نقل‌قول"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_CITE
    upper_name: "CITE"
    lower_name: "cite"
    generate_name: "cite"
    text: ["اثر", "ارجاع"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_DFN
    upper_name: "DFN"
    lower_name: "dfn"
    generate_name: "dfn"
    text: "اصطلاح"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ABBR
    upper_name: "ABBR"
    lower_name: "abbr"
    generate_name: "abbr"
    text: "اختصار"
    is_mother: false

  - id: AST_LAYOUT_TYPE_KBD
    upper_name: "KBD"
    lower_name: "kbd"
    generate_name: "kbd"
    fa: ["ورودی صفحه نمایش", "ورودی کیبورد"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_SAMP
    upper_name: "SAMP"
    lower_name: "samp"
    generate_name: "samp"
    text: "نمونه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_VAR
    upper_name: "VAR"
    lower_name: "var"
    generate_name: "var"
    text: "متغیر"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RUBY
    upper_name: "RUBY"
    lower_name: "ruby"
    generate_name: "ruby"
    text: "روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RT
    upper_name: "RT"
    lower_name: "rt"
    generate_name: "rt"
    text: "متن روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_RP
    upper_name: "RP"
    lower_name: "rp"
    generate_name: "rp"
    text: "جایگزین روبین"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BDI
    upper_name: "BDI"
    lower_name: "bdi"
    generate_name: "bdi"
    text: "جداگانه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_BDO
    upper_name: "BDO"
    lower_name: "bdo"
    generate_name: "bdo"
    text: "جهت دهی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_WBR
    upper_name: "WBR"
    lower_name: "wbr"
    generate_name: "wbr"
    text: "شکستن کلمه"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HEADER
    upper_name: "HEADER"
    lower_name: "header"
    generate_name: "header"
    text: ["سربخش", "سر بخش"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_FOOTER
    upper_name: "FOOTER"
    lower_name: "footer"
    generate_name: "footer"
    text: ["پاصفحه", "پا صفحه"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_NAV
    upper_name: "NAV"
    lower_name: "nav"
    generate_name: "nav"
    text: "ناوبری"
    is_mother: false

  - id: AST_LAYOUT_TYPE_SECTION
    upper_name: "SECTION"
    lower_name: "section"
    generate_name: "section"
    text: "بخش"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ARTICLE
    upper_name: "ARTICLE"
    lower_name: "article"
    generate_name: "article"
    text: "مقاله"
    is_mother: false

  - id: AST_LAYOUT_TYPE_ASIDE
    upper_name: "ASIDE"
    lower_name: "aside"
    generate_name: "aside"
    fa: ["جداگانه", "جدا گانه"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_MAIN
    upper_name: "MAIN"
    lower_name: "main"
    generate_name: "main"
    text: "اصلی"
    is_mother: false

  - id: AST_LAYOUT_TYPE_HGROUP
    upper_name: "HGROUP"
    lower_name: "hgroup"
    generate_name: "hgroup"
    fa: ["گروه سربخش", "گروه‌سربخش", "گروه‌سر بخش", "گروه سر بخش"]
    is_mother: false

  - id: AST_LAYOUT_TYPE_FIGURE
    upper_name: "FIGURE"
    lower_name: "figure"
    generate_name: "figure"
    text: "شکل"
    is_mother: false

  - type: AST_LAYOUT_TYPE_FIGCAPTION
    name: "FIGCAPTION"
    tag: "figcaption"
    generate_name: "figcaption"
    description: "زیرنویس شکل"
    repeat: false

  - type: AST_LAYOUT_TYPE_FIGCAPTION
    name: "FIGCAPTION"
    tag: "figcaption"
    generate_name: "figcaption"
    description: "زیر نویس شکل"
    repeat: true

  - type: AST_LAYOUT_TYPE_VIDEO
    name: "VIDEO"
    tag: "video"
    generate_name: "video"
    description: "فیلم"
    repeat: false

  - type: AST_LAYOUT_TYPE_AUDIO
    name: "AUDIO"
    tag: "audio"
    generate_name: "audio"
    description: "صدا"
    repeat: false

  - type: AST_LAYOUT_TYPE_IFRAME
    name: "IFRAME"
    tag: "iframe"
    generate_name: "iframe"
    description: "سایت"
    repeat: false

  - type: AST_LAYOUT_TYPE_CANVAS
    name: "CANVAS"
    tag: "canvas"
    generate_name: "canvas"
    description: "گرافیکی"
    repeat: false

  - type: AST_LAYOUT_TYPE_DETAILS
    name: "DETAILS"
    tag: "details"
    generate_name: "details"
    description: "جزئیات"
    repeat: false

  - type: AST_LAYOUT_TYPE_DETAILS
    name: "DETAILS"
    tag: "details"
    generate_name: "details"
    description: "جزییات"
    repeat: true

  - type: AST_LAYOUT_TYPE_SUMMARY
    name: "SUMMARY"
    tag: "summary"
    generate_name: "summary"
    description: "خلاصه"
    repeat: false

  - type: AST_LAYOUT_TYPE_DIALOG
    name: "DIALOG"
    tag: "dialog"
    generate_name: "dialog"
    description: "دیالوگ"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENU
    name: "MENU"
    tag: "menu"
    generate_name: "menu"
    description: "منو"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENUITEM
    name: "MENUITEM"
    tag: "menuitem"
    generate_name: "menuitem"
    description: "آیتم منو"
    repeat: false

  - type: AST_LAYOUT_TYPE_MENUITEM
    name: "MENUITEM"
    tag: "menuitem"
    generate_name: "menuitem"
    description: "مورد منو"
    repeat: true

  - type: AST_LAYOUT_TYPE_COMMAND
    name: "COMMAND"
    tag: "command"
    generate_name: "command"
    description: "فرمان"
    repeat: false

  - type: AST_LAYOUT_TYPE_UL
    name: "UL"
    tag: "ul"
    generate_name: "ul"
    description: "فهرست غیرمرتب"
    repeat: false

  - type: AST_LAYOUT_TYPE_UL
    name: "UL"
    tag: "ul"
    generate_name: "ul"
    description: "فهرست غیر مرتب"
    repeat: true

  - type: AST_LAYOUT_TYPE_OL
    name: "OL"
    tag: "ol"
    generate_name: "ol"
    description: "فهرست مرتب"
    repeat: false

  - type: AST_LAYOUT_TYPE_LI
    name: "LI"
    tag: "li"
    generate_name: "li"
    description: "مورد"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE
    name: "TABLE"
    tag: "table"
    generate_name: "table"
    description: "جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_HEADER
    name: "TABLE_HEADER"
    tag: "table_header"
    generate_name: "thead"
    description: "سرجدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_HEADER
    name: "TABLE_HEADER"
    tag: "table_header"
    generate_name: "thead"
    description: "سر جدول"
    repeat: true

  - type: AST_LAYOUT_TYPE_TABLE_BODY
    name: "TABLE_BODY"
    tag: "table_body"
    generate_name: "tbody"
    description: "بدنه جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_FOOTER
    name: "TABLE_FOOTER"
    tag: "table_footer"
    generate_name: "tfoot"
    description: "پاصفحه جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_FOOTER
    name: "TABLE_FOOTER"
    tag: "table_footer"
    generate_name: "tfoot"
    description: "پا صفحه جدول"
    repeat: true

  - type: AST_LAYOUT_TYPE_TABLE_TR
    name: "TABLE_TR"
    tag: "table_tr"
    generate_name: "tr"
    description: "ردیف"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TD
    name: "TABLE_TD"
    tag: "table_td"
    generate_name: "td"
    description: "سلول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TH
    name: "TABLE_TH"
    tag: "table_th"
    generate_name: "th"
    description: "سرسلول"
    repeat: false

  - type: AST_LAYOUT_TYPE_TABLE_TH
    tag: "table_th"
    generate_name: "th"
    description: "سر سلول"
    repeat: true

  - type: AST_LAYOUT_TYPE_CAPTION
    tag: "caption"
    generate_name: "caption"
    description: "عنوان جدول"
    repeat: false

  - type: AST_LAYOUT_TYPE_COL
    tag: "col"
    generate_name: "th"
    description: "ستون"
    repeat: false

  - type: AST_LAYOUT_TYPE_COLGROUP
    tag: "colgroup"
    generate_name: "colgroup"
    description: "گروه ستون‌ها"
    repeat: false

  - type: AST_LAYOUT_TYPE_COLGROUP
    generate_name: "colgroup"
    text:
      en: "colgroup"
      fa: "گروه ستون‌ ها"
    repeat: true

  - type: AST_LAYOUT_TYPE_INCLUDE
    generate_name: "include"
    text:
      en: "include"
      fa: "فراخوانی"
    is_mother: true

  - type: AST_LAYOUT_TYPE_BR
    generate_name: "br"
    text:
      en: "br"
      fa: "خط بعدی"
    is_mother: true

  - type: AST_LAYOUT_TYPE_HR
    generate_name: "hr"
    text:
      en: "hr"
      fa: "خط"
    is_mother: true

  - type: AST_LAYOUT_TYPE_INPUT
    generate_name: "input"
    text:
      en: "input"
      fa: "ورودی"
    is_mother: true

  - type: AST_LAYOUT_TYPE_IMG
    generate_name: "img"
    text:
      en: "img"
      fa: "تصویر"
    is_mother: true

  - type: AST_LAYOUT_TYPE_FONT
    generate_name: "font"
    text:
      en: "font"
      fa: "فونت"
    is_mother: true

  - type: AST_LAYOUT_TYPE_MEDIA
    generate_name: "@media"
    text:
      en: "responsive"
      fa: "واکنش گرا"
    is_mother: true

  - type: AST_LAYOUT_TYPE_MEDIA
    tag: "responsive"
    text:
      en: "@media"
      fa: "واکنش‌گرا"
    is_mother: true
