items:
  size_default:
    - generate_name: auto
      text:
        en: auto
        fa: خودکار
    - generate_name: max-content
      text:
        en: max-content
        fa: حداکثر محتوا
    - generate_name: min-content
      text:
        en: min-content
        fa: حداقل محتوا
    - generate_name: fit-content
      text:
        en: fit-content
        fa: فیت
  ast_layout_allowed_style_list_appearance:
    - generate_name: auto
      text:
        en: ""
        fa: مدیر کنترل پیش‌فرض
    - generate_name: button
      text:
        en: button
        fa: دکمه
    - generate_name: default
      text:
        en: default
        fa: پیشفرض
    - generate_name: text
      text:
        en: text
        fa: متن
    - generate_name: dropdown
      text:
        en: dropdown
        fa: منوی کشویی
    - generate_name: textfield
      text:
        en: textfield
        fa: فیلد متنی
    - generate_name: output
      text:
        en: output
        fa: خروجی
    - generate_name: none
      text:
        en: none
        fa: مخفی
