items:
  size_default:
    - generate_name: "auto"
      text:
        en: "auto"
        fa: "خودکار"
    - generate_name: "max-content"
      text:
        en: "max-content"
        fa: "حداکثر محتوا"
    - generate_name: "min-content"
      text:
        en: "min-content"
        fa: "حداقل محتوا"
    - generate_name: "fit-content"
      text:
        en: "fit-content"
        fa: "فیت"
  ast_layout_allowed_style_list_appearance:
    {"مدیر کنترل پیش‌فرض", "auto"},
    {"دکمه", "button"},
    {"پیش‌فرض", "default"},
    {"متن", "text"},
    {"منوی کشویی", "dropdown"},
    {"فیلد متنی", "textfield"},
    {"خروجی", "output"},
    {"مخفی", "none"},
