name: Build and Deploy WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Emscripten SDK
        uses: actions/cache@v4
        with:
          path: emsdk
          key: ${{ runner.os }}-emsdk-${{ hashFiles('emsdk/.emscripten') }}
          restore-keys: |
            ${{ runner.os }}-emsdk-

      - name: Install Emscripten (if not cached)
        run: |
          if [ ! -d "emsdk" ]; then
            git clone https://github.com/emscripten-core/emsdk.git
          fi
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Source Emscripten environment
        run: |
          echo "EMSDK=/home/runner/work/Salam/Salam/emsdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/home/runner/work/Salam/Salam/emsdk:/home/runner/work/Salam/Salam/emsdk/upstream/emscripten" >> $GITHUB_ENV
          source ./emsdk/emsdk_env.sh

      - name: Run WebAssembly build script
        run: |
          source emsdk/emsdk_env.sh
          cd src
          rm salam-wa.js
          bash build-webassembly.sh
            
      - name: List output files
        run: ls -la ./src/salam-wa*

      - uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          uploads: |
            src/salam-wa.js => ${{ secrets.SERVER_PATH }}salam-wa.js
            src/salam-wa.wasm => ${{ secrets.SERVER_PATH }}salam-wa.wasm
            src/salam-wa.html => ${{ secrets.SERVER_PATH }}salam-wa.html
