name: Build and Deploy WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Emscripten SDK
        uses: actions/cache@v4
        with:
          path: emsdk
          key: ${{ runner.os }}-emsdk-${{ hashFiles('emsdk/.emscripten') }}
          restore-keys: |
            ${{ runner.os }}-emsdk-

      - name: Install Emscripten (if not cached)
        run: |
          if [ ! -d "emsdk" ]; then
            git clone https://github.com/emscripten-core/emsdk.git
          fi
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Source Emscripten environment
        run: |
          echo "EMSDK=/home/runner/work/Salam/Salam/emsdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/home/runner/work/Salam/Salam/emsdk:/home/runner/work/Salam/Salam/emsdk/upstream/emscripten" >> $GITHUB_ENV
          source ./emsdk/emsdk_env.sh

      - name: Run WebAssembly build script
        run: |
          cd src
          source ../emsdk/emsdk_env.sh
          bash build-webassembly.sh

      - name: Copy files to SFTP server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: |
            src/salam-wa.html
            src/salam-wa.js
            src/salam-wa.wasm
          target: ${{ secrets.SERVER_PATH }}
