name: Build and Deploy WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emscripten
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 cmake
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Run WebAssembly build script
        run: |
          cd src
          bash build-webassembly.sh

      - name: Copy files to SFTP server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: |
            src/salam-wa.html
            src/salam-wa.js
            src/salam-wa.wasm
          target: ${{ secrets.SERVER_PATH }}
